## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Silver Concord LLC"
theme = "hugo-story"
baseURL = "https://www.silverconcord.com/"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "AWS architecture and cloud engineering consulting for secure, scalable, and compliant production systems."
  logo = "images/banner.jpg"
  favicon = true

