## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Silver Concord LLC"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "Software Consulting in Southeastern Wisconsin"
  logo = "images/banner.jpg"
  favicon = true

[Params.social]
  github = "https://github.com/OsborneSupremacy"
  email = "info@silverconcord.com"
  linkedin = "https://www.linkedin.com/in/benosborne/"
